[package]
name = "mobile_network_orchestrator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.24.1"
reqwest = { version = "0.11.17", features = ["json"] }
serde = "1.0.162"
tokio = { version = "1.28.1", features = ["full"] }
