[package]
name = "mobile_network_core_event"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = { version = "0.28.0", features = ["use-serde"] }
serde = "1.0.210"
url = "2.5.2"
